fix(ttfautohint): fix errors reported by namcap
alerque/aur pull request #72
Opened 2024-01-21 09:18 UTC by Zenvie

There are only two errors left unresolved:
1. The first error can be ignored: the file size of ttfautohint-1.8.4-3-x86_64.pkg.tar.zst is 1.5M, and the file size of /ttfautohint-1.8.4/doc/ttfautohint.pdf is 1.35 MB.
2. The second error might be a false positive.
```
ttfautohint W: Package was 72% docs by size; maybe you should split out a docs package
ttfautohint W: Unused shared library '/usr/lib/libm.so.6' by file ('usr/lib/libttfautohint.so.1.0.3')
```

2024-01-21 09:29 UTC, Zenvie commented on ttfautohint/PKGBUILD
> -    --with-freetype-config="pkg-config freetype2"
```
configure: WARNING: unrecognized options: --with-freetype-config
```

2024-01-21 11:32 UTC, alerque requested changes
Thanks for the contribution. Just a few nitpicks to make this mergable.

2024-01-21 11:32 UTC, alerque commented on ttfautohint/PKGBUILD
> +  install -Dm644 -t "$pkgdir/usr/share/licenses/$pkgname/" COPYING FTL.TXT GPLv2.TXT
A copy of the GPL license does not need to be installed because the SPDX identifier matches a license installed by the licenses package.

2024-01-21 11:32 UTC, alerque commented on ttfautohint/.SRCINFO
> +        pkgdesc = Provides automated hinting process for web fonts
Please do not convert tabs to spaces here. This file should be auto-generated by `makepkg --printsrcinfo` and then left alone.

2024-01-22 10:00 UTC, alerque approved these changes

2024-01-22 10:01 UTC, merged